default:
  pretrain_tasks: fill,contrast
  pretrain_epochs: 50
  pretrain_lr: 0.001
  pretrain_wd: 0.0
  pretrain_grad_clip:
  pretrain_display_step: 1
  pretrain_hg_batch_size: 32
  fill_batch_size: 256
  fill_num_negatives: 15
  fill_samples_per_epoch:
  fill_samples_per_graph_batch:
  fill_loss_weight: 1.0
  contrast_batch_size: 1024
  contrast_views_per_epoch: 1
  contrast_anchor_type: graph
  drop_incidence_rate: 0.2
  drop_feature_rate: 0.0
  contrast_temperature: 0.2
  contrast_loss_weight: 0.2

RHG_3:
  pretrain_tasks: fill,contrast
  pretrain_epochs: 50
  pretrain_hg_batch_size: 32
  fill_num_negatives: 15
  drop_incidence_rate: 0.2
  drop_feature_rate: 0.0
  fill_loss_weight: 1.0
  contrast_loss_weight: 0.2
